name: Firebase Emulator Action Example

on:
  push:
    branches:
      - main

jobs:
  run-emulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Start Firebase Emulator Suite
        uses: invertase/firebase-emulator-action@v1.0.1
        with:
          firebase-tools-version: 'latest'
          emulators: 'auth,firestore,functions,storage,database'
          project-id: "test-project"
          max-retries: "3"
          max-checks: "60"
          wait-time: "1"
          check-port: "8080"

      - name: Run Tests
