name: Firebase Emulator Action Example

on:
  push:
    branches:
      - main

jobs:
  run-emulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Start Firebase Emulator Suite
        uses: firebase-emulator-action@v1.0.1
        with:
          firebase-tools-version: 'latest'
          emulators: 'auth,firestore,functions,storage,database'
          project-id: 'my-test-project'

      - name: Run Tests
